# build.ps1 - generate AI tool configs from source agents
# Run this whenever you change anything in agents\ or rules\
#
# Usage:
#   .\build.ps1 -ProjectRoot "C:\dev\my-spring-project"
#
# Or from inside the project folder:
#   C:\Users\[youruser]\ai-config\build.ps1 -ProjectRoot (Get-Location)

param(
    [Parameter(Mandatory=$true)]
    [string]$ProjectRoot
)

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$AgentsDir = Join-Path $ScriptDir "agents"
$RulesDir  = Join-Path $ScriptDir "rules"
$SharedRules = Get-Content (Join-Path $RulesDir "shared.md") -Raw

Write-Host ""
Write-Host "Building AI configs from source..." -ForegroundColor Cyan
Write-Host "  Source:  $ScriptDir"
Write-Host "  Target:  $ProjectRoot"
Write-Host ""

# ─────────────────────────────────────────────
# 1. CLAUDE CODE  ->  .claude\CLAUDE.md
# ─────────────────────────────────────────────
$ClaudeDir = Join-Path $ProjectRoot ".claude"
New-Item -ItemType Directory -Force -Path $ClaudeDir | Out-Null
$ClaudeOut = Join-Path $ClaudeDir "CLAUDE.md"

$claudeSpecific = @"

## Claude Code Specific Rules
- You operate agentically and may read multiple files. Always state which files you are reading.
- Before editing any file, show the change you plan to make and wait for confirmation if it touches more than one class.
- Do not run shell commands that modify the filesystem without explicit approval.
"@

$claudeContent = "# Claude Code Instructions`n# Auto-generated by ai-config\build.ps1 - do not edit directly`n`n"
$claudeContent += $SharedRules
$claudeContent += "`n---`n"
$claudeContent += $claudeSpecific
$claudeContent += "`n---`n"

Get-ChildItem -Path $AgentsDir -Filter "*.md" | Sort-Object Name | ForEach-Object {
    $claudeContent += "`n"
    $claudeContent += Get-Content $_.FullName -Raw
    $claudeContent += "`n---`n"
}

Set-Content -Path $ClaudeOut -Value $claudeContent -Encoding UTF8
Write-Host "  Claude Code  ->  $ClaudeOut" -ForegroundColor Green

# ─────────────────────────────────────────────
# 2. WINDSURF  ->  .windsurf\rules\
# ─────────────────────────────────────────────
$WindsurfDir = Join-Path $ProjectRoot ".windsurf\rules"
New-Item -ItemType Directory -Force -Path $WindsurfDir | Out-Null

$windsurfSpecific = @"

## Windsurf Cascade Specific Rules
- You are agentic and can read/write files. Always confirm before deleting or renaming files.
- When running terminal commands, explain what each command does before running it.
- Do not install new dependencies (maven, gradle) without asking first.
"@

$sharedPlusWindsurf = $SharedRules + $windsurfSpecific
Set-Content -Path (Join-Path $WindsurfDir "00-shared.md") -Value $sharedPlusWindsurf -Encoding UTF8

$i = 1
Get-ChildItem -Path $AgentsDir -Filter "*.md" | Sort-Object Name | ForEach-Object {
    $prefix = "{0:D2}" -f $i
    $dest = Join-Path $WindsurfDir "$prefix-$($_.Name)"
    Copy-Item $_.FullName -Destination $dest
    $i++
}

Write-Host "  Windsurf     ->  $WindsurfDir\" -ForegroundColor Green

# ─────────────────────────────────────────────
# 3. GITHUB COPILOT  ->  .github\copilot-instructions.md
# ─────────────────────────────────────────────
$CopilotDir = Join-Path $ProjectRoot ".github"
New-Item -ItemType Directory -Force -Path $CopilotDir | Out-Null
$CopilotOut = Join-Path $CopilotDir "copilot-instructions.md"

$copilotSpecific = @"

## Copilot Specific Rules
- Inline suggestions should be production-ready, not demo code
- Prefer completing the pattern already established in the file
- Do not suggest imports that are not already used in the project
- For Spring Boot: prefer @Service/@Repository/@Controller over raw @Component

## Agent Roles Summary
When acting as each role, apply these priorities:
- **Backend Dev**: SOLID, constructor injection, proper exception handling
- **DB Specialist**: lazy loading by default, always consider migrations
- **QA**: JUnit 5, test unhappy paths, one assertion concept per test
- **Code Reviewer**: CRITICAL/MAJOR/MINOR/SUGGESTION priority system
"@

$copilotContent = "# GitHub Copilot Instructions`n# Auto-generated by ai-config\build.ps1 - do not edit directly`n`n"
$copilotContent += $SharedRules
$copilotContent += $copilotSpecific

Set-Content -Path $CopilotOut -Value $copilotContent -Encoding UTF8
Write-Host "  GitHub Copilot  ->  $CopilotOut" -ForegroundColor Green

# ─────────────────────────────────────────────
# Done
# ─────────────────────────────────────────────
Write-Host ""
Write-Host "Done. All configs generated." -ForegroundColor Cyan
Write-Host ""
Write-Host "Tip: create a shortcut for your project so you don't have to type the path each time:" -ForegroundColor Yellow
Write-Host "  Add this to your PowerShell profile (notepad `$PROFILE):"
Write-Host "  function build-ai { C:\Users\$env:USERNAME\ai-config\build.ps1 -ProjectRoot `"C:\path\to\your\project`" }"
Write-Host "  Then just type: build-ai"