#!/bin/bash
# build.sh — generate AI tool configs from source agents
# Run this whenever you change anything in agents/ or rules/
# Usage: ./build.sh [--project-root /path/to/your/project]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${1:-$(pwd)}"

AGENTS_DIR="$SCRIPT_DIR/agents"
RULES_DIR="$SCRIPT_DIR/rules"

echo "🔧 Building AI configs from source..."
echo "   Source:  $SCRIPT_DIR"
echo "   Target:  $PROJECT_ROOT"
echo ""

# ─────────────────────────────────────────────
# 1. CLAUDE CODE  →  .claude/CLAUDE.md
# ─────────────────────────────────────────────
CLAUDE_DIR="$PROJECT_ROOT/.claude"
mkdir -p "$CLAUDE_DIR"

cat > "$CLAUDE_DIR/CLAUDE.md" << 'HEADER'
# Claude Code Instructions
# Auto-generated by ai-config/build.sh — do not edit directly

HEADER

# Shared rules first
cat "$RULES_DIR/shared.md" >> "$CLAUDE_DIR/CLAUDE.md"
echo -e "\n---\n" >> "$CLAUDE_DIR/CLAUDE.md"

# Claude Code specific addition
cat >> "$CLAUDE_DIR/CLAUDE.md" << 'CLAUDE_SPECIFIC'
## Claude Code Specific Rules
- You operate agentically and may read multiple files. Always state which files you are reading.
- Before editing any file, show the change you plan to make and wait for confirmation if it touches more than one class.
- Do not run shell commands that modify the filesystem without explicit approval.
CLAUDE_SPECIFIC

echo -e "\n---\n" >> "$CLAUDE_DIR/CLAUDE.md"

# Append all agents
for agent in "$AGENTS_DIR"/*.md; do
  echo "" >> "$CLAUDE_DIR/CLAUDE.md"
  cat "$agent" >> "$CLAUDE_DIR/CLAUDE.md"
  echo -e "\n---\n" >> "$CLAUDE_DIR/CLAUDE.md"
done

echo "✅ Claude Code  → $CLAUDE_DIR/CLAUDE.md"

# ─────────────────────────────────────────────
# 2. WINDSURF  →  .windsurf/rules/
# ─────────────────────────────────────────────
WINDSURF_DIR="$PROJECT_ROOT/.windsurf/rules"
mkdir -p "$WINDSURF_DIR"

# Windsurf gets one file per agent + a shared rules file
cp "$RULES_DIR/shared.md" "$WINDSURF_DIR/00-shared.md"

# Windsurf-specific addition
cat >> "$WINDSURF_DIR/00-shared.md" << 'WINDSURF_SPECIFIC'

## Windsurf Cascade Specific Rules
- You are agentic and can read/write files. Always confirm before deleting or renaming files.
- When running terminal commands, explain what each command does before running it.
- Do not install new dependencies (npm, maven, gradle) without asking first.
WINDSURF_SPECIFIC

i=1
for agent in "$AGENTS_DIR"/*.md; do
  filename=$(basename "$agent")
  prefix=$(printf "%02d" $i)
  cp "$agent" "$WINDSURF_DIR/${prefix}-${filename}"
  i=$((i+1))
done

echo "✅ Windsurf      → $WINDSURF_DIR/"

# ─────────────────────────────────────────────
# 3. GITHUB COPILOT  →  .github/copilot-instructions.md
# ─────────────────────────────────────────────
COPILOT_DIR="$PROJECT_ROOT/.github"
mkdir -p "$COPILOT_DIR"

cat > "$COPILOT_DIR/copilot-instructions.md" << 'HEADER'
# GitHub Copilot Instructions
# Auto-generated by ai-config/build.sh — do not edit directly
# Note: Copilot uses this for inline suggestions — keep rules tight and actionable.

HEADER

cat "$RULES_DIR/shared.md" >> "$COPILOT_DIR/copilot-instructions.md"

cat >> "$COPILOT_DIR/copilot-instructions.md" << 'COPILOT_SPECIFIC'

## Copilot Specific Rules
- Inline suggestions should be production-ready, not demo code
- Prefer completing the pattern already established in the file
- Do not suggest imports that are not already used in the project
- For Spring Boot: prefer @Service/@Repository/@Controller over raw @Component
COPILOT_SPECIFIC

# Copilot gets a condensed agent summary (not full files — it's inline, not chat)
echo -e "\n## Agent Roles Summary\n" >> "$COPILOT_DIR/copilot-instructions.md"
echo "When acting as each role, apply these priorities:" >> "$COPILOT_DIR/copilot-instructions.md"
echo "- **Backend Dev**: SOLID, constructor injection, proper exception handling" >> "$COPILOT_DIR/copilot-instructions.md"
echo "- **DB Specialist**: lazy loading by default, always consider migrations" >> "$COPILOT_DIR/copilot-instructions.md"
echo "- **QA**: JUnit 5, test unhappy paths, one assertion concept per test" >> "$COPILOT_DIR/copilot-instructions.md"
echo "- **Code Reviewer**: CRITICAL/MAJOR/MINOR/SUGGESTION priority system" >> "$COPILOT_DIR/copilot-instructions.md"

echo "✅ GitHub Copilot → $COPILOT_DIR/copilot-instructions.md"

# ─────────────────────────────────────────────
# Done
# ─────────────────────────────────────────────
echo ""
echo "🎉 Done. All configs generated."
echo ""
echo "To install as a git pre-commit hook (optional):"
echo "  cp $SCRIPT_DIR/build.sh $PROJECT_ROOT/.git/hooks/pre-commit"
echo "  chmod +x $PROJECT_ROOT/.git/hooks/pre-commit"
